DROP TABLE IF EXISTS T_BIOGRAPHY_TEMPLATE CASCADE;
CREATE TABLE T_BIOGRAPHY_TEMPLATE (
 TEMPLATE_ID integer NOT NULL,
 TEMPLATE_PATH VARCHAR(30),
 TEMPLATE_NAME VARCHAR(20),
 TEMPLATE_DESCRIPTION VARCHAR(20)
);

ALTER TABLE T_BIOGRAPHY_TEMPLATE ADD CONSTRAINT PK_BIOGRAPHY_TEMPLATE PRIMARY KEY (TEMPLATE_ID);
DROP SEQUENCE IF EXISTS T_BIOGRAPHY_TEMPLATE_ID_SEQ CASCADE ;
CREATE SEQUENCE T_BIOGRAPHY_TEMPLATE_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE T_BIOGRAPHY_TEMPLATE ALTER COLUMN TEMPLATE_ID SET DEFAULT nextval('T_BIOGRAPHY_TEMPLATE_ID_SEQ');


DROP TABLE IF EXISTS T_MEDIA CASCADE;
CREATE TABLE T_MEDIA (
 MEDIA_ID integer NOT NULL,
 MEDIA_TIME CHAR(10),
 MEDIA_PLACE CHAR(10),
 MEDIAL_URL CHAR(10),
 MEDIA_URL_PARAM CHAR(10),
 MEDIA_BRIEF CHAR(10)
);

ALTER TABLE T_MEDIA ADD CONSTRAINT PK_T_MEDIA PRIMARY KEY (MEDIA_ID);
DROP SEQUENCE IF EXISTS T_MEDIA_ID_SEQ CASCADE ;
CREATE SEQUENCE T_MEDIA_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE T_MEDIA ALTER COLUMN MEDIA_ID SET DEFAULT nextval('T_MEDIA_ID_SEQ');


DROP TABLE IF EXISTS T_MEMBER CASCADE;
CREATE TABLE T_MEMBER (
 MEMBER_ID integer NOT NULL,
 MEMBER_NAME VARCHAR(20),
 MEMBER_BIRTHDAY DATE,
 MEMBER_DEADFLG CHAR(1),
 MEMBER_DEADDAY DATE,
 MEMBER_SEX CHAR(1),
 MEMBER_BIRTHPLACE VARCHAR(30),
 MEMBER_DEADPALCE VARCHAR(30),
 MEMBER_PHACEPHOTO VARCHAR(30)
);

ALTER TABLE T_MEMBER ADD CONSTRAINT PK_T_MEMBER PRIMARY KEY (MEMBER_ID);

DROP SEQUENCE IF EXISTS T_MEMBER_ID_SEQ CASCADE ;
CREATE SEQUENCE T_MEMBER_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE T_MEMBER ALTER COLUMN MEMBER_ID SET DEFAULT nextval('T_MEMBER_ID_SEQ');


DROP TABLE IF EXISTS T_MEDIA_TEXT CASCADE;
CREATE TABLE T_MEDIA_TEXT (
 TEXT_ID integer NOT NULL,
 TEXT_CONTENT CHAR(10),
 TEXT_TYPE CHAR(10),
 TEXT_SUMMARY CHAR(10),
 MEDIA_ID integer
);

ALTER TABLE T_MEDIA_TEXT ADD CONSTRAINT PK_T_MEDIA_TEXT PRIMARY KEY (TEXT_ID);

DROP SEQUENCE IF EXISTS T_MEDIA_TEXT_ID_SEQ CASCADE ;
CREATE SEQUENCE T_MEDIA_TEXT_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE T_MEDIA_TEXT ALTER COLUMN TEXT_ID SET DEFAULT nextval('T_MEDIA_TEXT_ID_SEQ');


DROP TABLE IF EXISTS M_AUTHORITY CASCADE;
CREATE TABLE M_AUTHORITY (
 AUTHORITY_ID integer NOT NULL,
 AUTHORITY_NAME CHAR(10)
);

ALTER TABLE M_AUTHORITY ADD CONSTRAINT PK_M_AUTHORITY PRIMARY KEY (AUTHORITY_ID);

DROP SEQUENCE IF EXISTS M_AUTHORITY_ID_SEQ CASCADE ;
CREATE SEQUENCE M_AUTHORITY_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE M_AUTHORITY ALTER COLUMN AUTHORITY_ID SET DEFAULT nextval('M_AUTHORITY_ID_SEQ');


DROP TABLE IF EXISTS T_MEDIA_IMAGE CASCADE;
CREATE TABLE T_MEDIA_IMAGE (
 IMAGE_ID integer NOT NULL,
 IMAGE_FORMAT CHAR(10),
 IMAGE_SIZE CHAR(10),
 IMAGE_PATH CHAR(10),
 IMAGE_SUMMARY CHAR(10),
 MEDIA_ID integer
);

ALTER TABLE T_MEDIA_IMAGE ADD CONSTRAINT PK_T_MEDIA_IMAGE PRIMARY KEY (IMAGE_ID);

DROP SEQUENCE IF EXISTS T_MEDIA_IMAGE_ID_SEQ CASCADE ;
CREATE SEQUENCE T_MEDIA_IMAGE_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE T_MEDIA_IMAGE ALTER COLUMN IMAGE_ID SET DEFAULT nextval('T_MEDIA_IMAGE_ID_SEQ');


DROP TABLE IF EXISTS T_USER CASCADE;
CREATE TABLE T_USER (
 USER_ID integer NOT NULL,
 USER_MAIL VARCHAR(20) NOT NULL,
 USER_PASSWORD VARCHAR(15) NOT NULL,
 USER_PHONENO VARCHAR(30),
 USER_ADDRESS VARCHAR(30),
 MEMBER_ID integer NOT NULL
);

ALTER TABLE T_USER ADD CONSTRAINT PK_T_USER PRIMARY KEY (USER_ID);
DROP SEQUENCE IF EXISTS T_USER_ID_SEQ CASCADE ;
CREATE SEQUENCE T_USER_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE T_USER ALTER COLUMN USER_ID SET DEFAULT nextval('T_USER_ID_SEQ');


DROP TABLE IF EXISTS T_MESSAGE CASCADE;
CREATE TABLE T_MESSAGE (
 MESSAGE_ID integer NOT NULL,
 MESSAGE_SOURCE_TYPE CHAR(1) DEFAULT '0' NOT NULL,
 MESSAGE_SORCE_NAME VARCHAR(30) DEFAULT '管理员' NOT NULL,
 MESSAGE_CONTEXT VARCHAR(500),
 MESSAGE_TIME DATE DEFAULT 'NOW()' NOT NULL,
 MESSAGE_LEVEL CHAR(1) DEFAULT '0' NOT NULL,
 MESSAGE_STATUS CHAR(1) DEFAULT '0' NOT NULL,
 MESSAGE_CONTACE VARCHAR(30),
 USER_ID integer
);

ALTER TABLE T_MESSAGE ADD CONSTRAINT PK_T_MESSAGE PRIMARY KEY (MESSAGE_ID);
DROP SEQUENCE IF EXISTS T_MESSAGE_ID_SEQ CASCADE ;
CREATE SEQUENCE T_MESSAGE_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE T_MESSAGE ALTER COLUMN MESSAGE_ID SET DEFAULT nextval('T_MESSAGE_ID_SEQ');


DROP TABLE IF EXISTS M_ALL_HERALDRY CASCADE;
CREATE TABLE M_ALL_HERALDRY (
 HERALDRY_ID integer NOT NULL,
 HERALDRY_NAME CHAR(10),
 HERALDRY_DESCRIPT CHAR(10),
 HERALDRY_PATH CHAR(10)
);

ALTER TABLE M_ALL_HERALDRY ADD CONSTRAINT PK_M_ALL_HERALDRY PRIMARY KEY (HERALDRY_ID);

DROP SEQUENCE IF EXISTS M_ALL_HERALDRY_ID_SEQ CASCADE ;
CREATE SEQUENCE M_ALL_HERALDRY_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE M_ALL_HERALDRY ALTER COLUMN HERALDRY_ID SET DEFAULT nextval('M_ALL_HERALDRY_ID_SEQ');


DROP TABLE IF EXISTS T_MEDIA_VIDEO CASCADE;
CREATE TABLE T_MEDIA_VIDEO (
 VIDEO_ID integer NOT NULL,
 VEDIO_FORMAT CHAR(10),
 VIDEO_SIZE CHAR(10),
 VIDEO_PATH CHAR(10),
 VIDEO_SUMMARY CHAR(10),
 MEDIA_ID integer
);

ALTER TABLE T_MEDIA_VIDEO ADD CONSTRAINT PK_T_MEDIA_VIDEO PRIMARY KEY (VIDEO_ID);

DROP SEQUENCE IF EXISTS T_MEDIA_VIDEO_ID_SEQ CASCADE ;
CREATE SEQUENCE T_MEDIA_VIDEO_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE T_MEDIA_VIDEO ALTER COLUMN VIDEO_ID SET DEFAULT nextval('T_MEDIA_VIDEO_ID_SEQ');


DROP TABLE IF EXISTS T_ACCESS CASCADE;
CREATE TABLE T_ACCESS (
 ACCESS_ID integer NOT NULL,
 ACCESS_SHORT_URL INT,
 ACCESS_NORMAL_URL CHAR(10),
 ACCESS_ERCODE CHAR(10)
);

ALTER TABLE T_ACCESS ADD CONSTRAINT PK_T_ACCESS PRIMARY KEY (ACCESS_ID);

DROP SEQUENCE IF EXISTS T_ACCESS_ID_SEQ CASCADE ;
CREATE SEQUENCE T_ACCESS_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE T_ACCESS ALTER COLUMN ACCESS_ID SET DEFAULT nextval('T_ACCESS_ID_SEQ');


DROP TABLE IF EXISTS T_CEMETERY CASCADE;
CREATE TABLE T_CEMETERY (
 CEMETERY_ID integer NOT NULL,
 CEMETERY_NAME CHAR(10),
 CEMETERY_ADDRESS CHAR(10),
 CEMETERY_MAP CHAR(10),
 CEMETERY_URL CHAR(10),
 CEMETERY_MAIL CHAR(10),
 CEMETERY_IPHONE CHAR(10),
 CEMETERY_STATUS CHAR(10),
 CEMETERY_PROVIDER_TYPE CHAR(10),
 CEMETERY_PROVIDER_CONTACT CHAR(10)
);

ALTER TABLE T_CEMETERY ADD CONSTRAINT PK_T_CEMETERY PRIMARY KEY (CEMETERY_ID);

DROP SEQUENCE IF EXISTS T_CEMETERY_ID_SEQ CASCADE ;
CREATE SEQUENCE T_CEMETERY_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE T_CEMETERY ALTER COLUMN CEMETERY_ID SET DEFAULT nextval('T_CEMETERY_ID_SEQ');


DROP TABLE IF EXISTS T_MEDIA_AUDIO CASCADE;
CREATE TABLE T_MEDIA_AUDIO (
 AUDIO_ID integer NOT NULL,
 AUDIO_FORMAT CHAR(10),
 AUDIO_SIZE CHAR(10),
 AUDIO_PATH CHAR(10),
 MEDIA_ID integer
);

ALTER TABLE T_MEDIA_AUDIO ADD CONSTRAINT PK_T_MEDIA_AUDIO PRIMARY KEY (AUDIO_ID);

DROP SEQUENCE IF EXISTS T_MEDIA_AUDIO_ID_SEQ CASCADE ;
CREATE SEQUENCE T_MEDIA_AUDIO_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE T_MEDIA_AUDIO ALTER COLUMN AUDIO_ID SET DEFAULT nextval('T_MEDIA_AUDIO_ID_SEQ');


DROP TABLE IF EXISTS T_RELATION CASCADE;
CREATE TABLE T_RELATION (
 RELATION_ID integer NOT NULL,
 RELATION_NEEDPWD CHAR(1),
 RELATION_PASSWORD VARCHAR(10),
 USER_ID integer,
 TEMPLATE_ID integer,
 FAMILY_MEMBER_ID integer,
 MEMBER_ID integer NOT NULL
);

ALTER TABLE T_RELATION ADD CONSTRAINT PK_T_RELATION PRIMARY KEY (RELATION_ID);

DROP SEQUENCE IF EXISTS T_RELATION_ID_SEQ CASCADE ;
CREATE SEQUENCE T_RELATION_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE T_RELATION ALTER COLUMN RELATION_ID SET DEFAULT nextval('T_RELATION_ID_SEQ');


DROP TABLE IF EXISTS T_RELATION_ACCESS CASCADE;
CREATE TABLE T_RELATION_ACCESS (
 RELATION_ID integer NOT NULL,
 ACCESS_ID integer  NOT NULL
);

ALTER TABLE T_RELATION_ACCESS ADD CONSTRAINT PK_T_RELATION_ACCESS PRIMARY KEY (RELATION_ID,ACCESS_ID);


DROP TABLE IF EXISTS T_RELATION_PRIVACE CASCADE;
CREATE TABLE T_RELATION_PRIVACE (
 RELATION_PRIVACE_ID integer NOT NULL,
 RELATION_ID integer NOT NULL,
 PRIVACE_ID integer,
 PRIVACE_FLG integer,
);

ALTER TABLE T_RELATION_PRIVACE ADD CONSTRAINT PK_T_RELATION_PRIVACE PRIMARY KEY (RELATION_PRIVACE_ID);
DROP SEQUENCE IF EXISTS T_RELATION_PRIVACE_ID_SEQ CASCADE ;
CREATE SEQUENCE T_RELATION_PRIVACE_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE T_RELATION_PRIVACE ALTER COLUMN RELATION_PRIVACE_ID SET DEFAULT nextval('T_RELATION_PRIVACE_ID_SEQ');

DROP TABLE IF EXISTS M_PRIVACE CASCADE;
CREATE TABLE M_PRIVACE (
 PRIVACE_ID integer NOT NULL,
 PRIVACE_CLASS integer NOT NULL,
 PRIVACE_CONTENT VARCHAR(30),
 PRIVACE_TYPE integer,
);

ALTER TABLE M_PRIVACE ADD CONSTRAINT PK_M_PRIVACE_PRIVACE PRIMARY KEY (PRIVACE_ID);
DROP SEQUENCE IF EXISTS M_PRIVACE_ID_SEQ CASCADE ;
CREATE SEQUENCE M_PRIVACE_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE M_PRIVACE ALTER COLUMN PRIVACE_ID SET DEFAULT nextval('M_PRIVACE_ID_SEQ');


DROP TABLE IF EXISTS T_GRAVE CASCADE;
CREATE TABLE T_GRAVE (
 GRAVE_ID integer NOT NULL,
 GRAVE_EPITAPH CHAR(10),
 GRAVE_PRAYER CHAR(10),
 RELATION_ID integer NOT NULL,
 GRAVE_IMG CHAR(10),
 GRAVE_CEMETERY_NAME CHAR(10),
 GRAVE_CEMETERY_ADDRESS CHAR(10),
 CEMETERY_ID integer
);

ALTER TABLE T_GRAVE ADD CONSTRAINT PK_T_GRAVE PRIMARY KEY (GRAVE_ID);


DROP TABLE IF EXISTS T_GRAVE_CONTACT CASCADE;
CREATE TABLE T_GRAVE_CONTACT (
 GRAVE_CONTACT_ID integer NOT NULL,
 CONTACT_RELATION CHAR(10),
 CONTACT_NAMW CHAR(10),
 CONTACT_IPHONE CHAR(10),
 CONTACT_MAIL CHAR(10),
 CONTACT_ADDRESS CHAR(10),
 GRAVE_ID integer
);

ALTER TABLE T_GRAVE_CONTACT ADD CONSTRAINT PK_T_GRAVE_CONTACT PRIMARY KEY (GRAVE_CONTACT_ID);


DROP TABLE IF EXISTS T_FAMILY CASCADE;
CREATE TABLE T_FAMILY (
 FAMILY_ID integer NOT NULL,
 FAMILY_MEMBER_NUMBER CHAR(10),
 FAMILY_CREATETIME DATE,
 FAMILY_HERALDRY CHAR(10),
 FAMILY_INJUNCTION CHAR(10),
 FAMILY_PASSWORD CHAR(10),
 FAMILY_PASSWORD_FLG CHAR(10),
 FAMILY_DESCRIPT CHAR(10),
 DELETE_FLG CHAR(10),
 USER_ID integer
);

ALTER TABLE T_FAMILY ADD CONSTRAINT PK_T_FAMILY PRIMARY KEY (FAMILY_ID);


DROP TABLE IF EXISTS T_FAMILY_NOTICE CASCADE;
CREATE TABLE T_FAMILY_NOTICE (
 FAMILY_ID integer NOT NULL,
 NOTICE_CONTENT CHAR(10),
 NOTICE_LEVEL CHAR(10),
 NOTICE_DATE CHAR(10),
 NOTICE_END_DATE CHAR(10)
);

ALTER TABLE T_FAMILY_NOTICE ADD CONSTRAINT PK_T_FAMILY_NOTICE PRIMARY KEY (FAMILY_ID);


DROP TABLE IF EXISTS T_FAMILY_MEMBER CASCADE;
CREATE TABLE T_FAMILY_MEMBER (
 FAMILY_MEMBER_ID integer NOT NULL,
 FAMILY_ID integer NOT NULL,
 RELATION_ID integer,
 USER_ID_1 integer,
 FAMILY_MEMBER_GENERATION CHAR(10),
 PARENT_ID integer,
 MOTHER_ID integer,
 WIFE_ID integer,
 MEMBER_TYPE CHAR(10),
 MEMBER_ID integer
);

ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT PK_T_FAMILY_MEMBER PRIMARY KEY (FAMILY_MEMBER_ID);


DROP TABLE IF EXISTS T_FAMILY_MEMBER_AUTHORITY CASCADE;
CREATE TABLE T_FAMILY_MEMBER_AUTHORITY (
 FAMILY_MEMBER_ID integer NOT NULL,
 FAMILY_ID integer NOT NULL,
 AUTHORITY_ID integer,
 AUTHORITY_STATUS CHAR(10)
);

ALTER TABLE T_FAMILY_MEMBER_AUTHORITY ADD CONSTRAINT PK_T_FAMILY_MEMBER_AUTHORITY PRIMARY KEY (FAMILY_MEMBER_ID,FAMILY_ID);


DROP TABLE IF EXISTS T_FAMILY_APPLY CASCADE;
CREATE TABLE T_FAMILY_APPLY (
 APPLY_ID integer NOT NULL,
 USER_ID integer,
 FAMILY_ID integer,
 FAMILY_MEMBER_ID integer,
 APPLY_FAMILY_ADMIN integer,
 APPLY_STATUS CHAR(10),
 APPLY_COMMENT CHAR(10),
 REPLY_COMMENT CHAR(10),
 MEMBER_ID integer
);

ALTER TABLE T_FAMILY_APPLY ADD CONSTRAINT PK_T_FAMILY_APPLY PRIMARY KEY (APPLY_ID);


DROP TABLE IF EXISTS T_FAMILY_ACCESS CASCADE;
CREATE TABLE T_FAMILY_ACCESS (
 FAMILY_ID integer NOT NULL,
 ACCESS_ID integer
);

ALTER TABLE T_FAMILY_ACCESS ADD CONSTRAINT PK_T_FAMILY_ACCESS PRIMARY KEY (FAMILY_ID);


DROP TABLE IF EXISTS T_MEMORY CASCADE;
CREATE TABLE T_MEMORY (
 MEMORY_ID integer NOT NULL,
 MEMOEY_CONTENT CHAR(10),
 MEMORY_DATE CHAR(10),
 MEMORY_AUTHOR CHAR(10),
 MEMORY_ISPUBLIC CHAR(10),
 MEMORY_DELETEFLG CHAR(10),
 RELATION_ID integer NOT NULL,
 MEMORY_IMAGE CHAR(10)
);

ALTER TABLE T_MEMORY ADD CONSTRAINT PK_T_MEMORY PRIMARY KEY (MEMORY_ID);


DROP TABLE IF EXISTS T_RELATION_MEDIA_TEXT CASCADE;
CREATE TABLE T_RELATION_MEDIA_TEXT (
 RELATION_ID integer NOT NULL,
 TEXT_ID integer NOT NULL
);

ALTER TABLE T_RELATION_MEDIA_TEXT ADD CONSTRAINT PK_T_RELATION_MEDIA_TEXT PRIMARY KEY (RELATION_ID,TEXT_ID);


DROP TABLE IF EXISTS T_FAMILY_MEDIA_TEXT CASCADE;
CREATE TABLE T_FAMILY_MEDIA_TEXT (
 FAMILY_ID integer NOT NULL,
 TEXT_ID integer NOT NULL
);

ALTER TABLE T_FAMILY_MEDIA_TEXT ADD CONSTRAINT PK_T_FAMILY_MEDIA_TEXT PRIMARY KEY (FAMILY_ID,TEXT_ID);


DROP TABLE IF EXISTS T_RELATION_MEDIA_IMAGE CASCADE;
CREATE TABLE T_RELATION_MEDIA_IMAGE (
 RELATION_ID integer NOT NULL,
 IMAGE_ID integer NOT NULL
);

ALTER TABLE T_RELATION_MEDIA_IMAGE ADD CONSTRAINT PK_T_RELATION_MEDIA_IMAGE PRIMARY KEY (RELATION_ID,IMAGE_ID);


DROP TABLE IF EXISTS T_FAMILY_MEDIA_IMAGE CASCADE;
CREATE TABLE T_FAMILY_MEDIA_IMAGE (
 FAMILY_ID integer NOT NULL,
 IMAGE_ID integer NOT NULL
);

ALTER TABLE T_FAMILY_MEDIA_IMAGE ADD CONSTRAINT PK_T_FAMILY_MEDIA_IMAGE PRIMARY KEY (FAMILY_ID,IMAGE_ID);


DROP TABLE IF EXISTS T_RELATION_MEDIA_VIDEO CASCADE;
CREATE TABLE T_RELATION_MEDIA_VIDEO (
 RELATION_ID integer NOT NULL,
 VIDEO_ID integer NOT NULL
);

ALTER TABLE T_RELATION_MEDIA_VIDEO ADD CONSTRAINT PK_T_RELATION_MEDIA_VIDEO PRIMARY KEY (RELATION_ID,VIDEO_ID);


DROP TABLE IF EXISTS T_FAMILY_MEDIA_VIDEO CASCADE;
CREATE TABLE T_FAMILY_MEDIA_VIDEO (
 FAMILY_ID integer NOT NULL,
 VIDEO_ID integer NOT NULL
);

ALTER TABLE T_FAMILY_MEDIA_VIDEO ADD CONSTRAINT PK_T_FAMILY_MEDIA_VIDEO PRIMARY KEY (FAMILY_ID,VIDEO_ID);


DROP TABLE IF EXISTS T_RELATION_MEDIA_AUDIO CASCADE;
CREATE TABLE T_RELATION_MEDIA_AUDIO (
 RELATION_ID integer NOT NULL,
 AUDIO_ID integer NOT NULL
);

ALTER TABLE T_RELATION_MEDIA_AUDIO ADD CONSTRAINT PK_T_RELATION_MEDIA_AUDIO PRIMARY KEY (RELATION_ID,AUDIO_ID);


DROP TABLE IF EXISTS T_FAMILY_MEDIA_AUDIO CASCADE;
CREATE TABLE T_FAMILY_MEDIA_AUDIO (
 FAMILY_ID integer NOT NULL,
 AUDIO_ID integer NOT NULL
);

ALTER TABLE T_FAMILY_MEDIA_AUDIO ADD CONSTRAINT PK_T_FAMILY_MEDIA_AUDIO PRIMARY KEY (FAMILY_ID,AUDIO_ID);


DROP TABLE IF EXISTS T_FAMILY_RELATION CASCADE;
CREATE TABLE T_FAMILY_RELATION (
 FAMILY_ID integer NOT NULL,
 RELATION_FAMILY_ID integer,
 RELATION_DES CHAR(10)
);

ALTER TABLE T_FAMILY_RELATION ADD CONSTRAINT PK_T_FAMILY_RELATION PRIMARY KEY (FAMILY_ID);


ALTER TABLE T_MEDIA_TEXT ADD CONSTRAINT FK_T_MEDIA_TEXT_0 FOREIGN KEY (MEDIA_ID) REFERENCES T_MEDIA (MEDIA_ID);


ALTER TABLE T_MEDIA_IMAGE ADD CONSTRAINT FK_T_MEDIA_IMAGE_0 FOREIGN KEY (MEDIA_ID) REFERENCES T_MEDIA (MEDIA_ID);


ALTER TABLE T_USER ADD CONSTRAINT FK_T_USER_0 FOREIGN KEY (MEMBER_ID) REFERENCES T_MEMBER (MEMBER_ID);


ALTER TABLE T_MESSAGE ADD CONSTRAINT FK_T_MESSAGE_0 FOREIGN KEY (USER_ID) REFERENCES T_USER (USER_ID);


ALTER TABLE T_MEDIA_VIDEO ADD CONSTRAINT FK_T_MEDIA_VIDEO_0 FOREIGN KEY (MEDIA_ID) REFERENCES T_MEDIA (MEDIA_ID);


ALTER TABLE T_MEDIA_AUDIO ADD CONSTRAINT FK_T_MEDIA_AUDIO_0 FOREIGN KEY (MEDIA_ID) REFERENCES T_MEDIA (MEDIA_ID);


ALTER TABLE T_RELATION ADD CONSTRAINT FK_T_RELATION_0 FOREIGN KEY (USER_ID) REFERENCES T_USER (USER_ID);
ALTER TABLE T_RELATION ADD CONSTRAINT FK_T_RELATION_1 FOREIGN KEY (TEMPLATE_ID) REFERENCES BIOGRAPHY_TEMPLATE (TEMPLATE_ID);
ALTER TABLE T_RELATION ADD CONSTRAINT FK_T_RELATION_2 FOREIGN KEY (MEMBER_ID) REFERENCES T_MEMBER (MEMBER_ID);


ALTER TABLE T_RELATION_ACCESS ADD CONSTRAINT FK_T_RELATION_ACCESS_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_RELATION_ACCESS ADD CONSTRAINT FK_T_RELATION_ACCESS_1 FOREIGN KEY (ACCESS_ID) REFERENCES T_ACCESS (ACCESS_ID);


ALTER TABLE T_RELATION_PRIVACE ADD CONSTRAINT FK_T_RELATION_PRIVACE_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);


ALTER TABLE T_GRAVE ADD CONSTRAINT FK_T_GRAVE_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_GRAVE ADD CONSTRAINT FK_T_GRAVE_1 FOREIGN KEY (CEMETERY_ID) REFERENCES T_CEMETERY (CEMETERY_ID);


ALTER TABLE T_GRAVE_CONTACT ADD CONSTRAINT FK_T_GRAVE_CONTACT_0 FOREIGN KEY (GRAVE_ID) REFERENCES T_GRAVE (GRAVE_ID);


ALTER TABLE T_FAMILY ADD CONSTRAINT FK_T_FAMILY_0 FOREIGN KEY (USER_ID) REFERENCES T_USER (USER_ID);


ALTER TABLE T_FAMILY_NOTICE ADD CONSTRAINT FK_T_FAMILY_NOTICE_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);


ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_1 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_2 FOREIGN KEY (USER_ID_1) REFERENCES T_USER (USER_ID);
ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_3 FOREIGN KEY (PARENT_ID) REFERENCES T_FAMILY_MEMBER (FAMILY_MEMBER_ID);
ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_4 FOREIGN KEY (MOTHER_ID) REFERENCES T_FAMILY_MEMBER (FAMILY_MEMBER_ID);
ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_5 FOREIGN KEY (WIFE_ID) REFERENCES T_FAMILY_MEMBER (FAMILY_MEMBER_ID);
ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_6 FOREIGN KEY (MEMBER_ID) REFERENCES T_MEMBER (MEMBER_ID);


ALTER TABLE T_FAMILY_MEMBER_AUTHORITY ADD CONSTRAINT FK_T_FAMILY_MEMBER_AUTHORITY_0 FOREIGN KEY (FAMILY_MEMBER_ID) REFERENCES T_FAMILY_MEMBER (FAMILY_MEMBER_ID);
ALTER TABLE T_FAMILY_MEMBER_AUTHORITY ADD CONSTRAINT FK_T_FAMILY_MEMBER_AUTHORITY_1 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_MEMBER_AUTHORITY ADD CONSTRAINT FK_T_FAMILY_MEMBER_AUTHORITY_2 FOREIGN KEY (AUTHORITY_ID) REFERENCES M_AUTHORITY (AUTHORITY_ID);


ALTER TABLE T_FAMILY_APPLY ADD CONSTRAINT FK_T_FAMILY_APPLY_0 FOREIGN KEY (USER_ID) REFERENCES T_USER (USER_ID);
ALTER TABLE T_FAMILY_APPLY ADD CONSTRAINT FK_T_FAMILY_APPLY_1 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_APPLY ADD CONSTRAINT FK_T_FAMILY_APPLY_2 FOREIGN KEY (FAMILY_MEMBER_ID) REFERENCES T_FAMILY_MEMBER (FAMILY_MEMBER_ID);
ALTER TABLE T_FAMILY_APPLY ADD CONSTRAINT FK_T_FAMILY_APPLY_3 FOREIGN KEY (APPLY_FAMILY_ADMIN) REFERENCES T_USER (USER_ID);
ALTER TABLE T_FAMILY_APPLY ADD CONSTRAINT FK_T_FAMILY_APPLY_4 FOREIGN KEY (MEMBER_ID) REFERENCES T_MEMBER (MEMBER_ID);


ALTER TABLE T_FAMILY_ACCESS ADD CONSTRAINT FK_T_FAMILY_ACCESS_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_ACCESS ADD CONSTRAINT FK_T_FAMILY_ACCESS_1 FOREIGN KEY (ACCESS_ID) REFERENCES T_ACCESS (ACCESS_ID);


ALTER TABLE T_MEMORY ADD CONSTRAINT FK_T_MEMORY_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);


ALTER TABLE T_RELATION_MEDIA_TEXT ADD CONSTRAINT FK_T_RELATION_MEDIA_TEXT_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_RELATION_MEDIA_TEXT ADD CONSTRAINT FK_T_RELATION_MEDIA_TEXT_1 FOREIGN KEY (TEXT_ID) REFERENCES T_MEDIA_TEXT (TEXT_ID);


ALTER TABLE T_FAMILY_MEDIA_TEXT ADD CONSTRAINT FK_T_FAMILY_MEDIA_TEXT_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_MEDIA_TEXT ADD CONSTRAINT FK_T_FAMILY_MEDIA_TEXT_1 FOREIGN KEY (TEXT_ID) REFERENCES T_MEDIA_TEXT (TEXT_ID);


ALTER TABLE T_RELATION_MEDIA_IMAGE ADD CONSTRAINT FK_T_RELATION_MEDIA_IMAGE_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_RELATION_MEDIA_IMAGE ADD CONSTRAINT FK_T_RELATION_MEDIA_IMAGE_1 FOREIGN KEY (IMAGE_ID) REFERENCES T_MEDIA_IMAGE (IMAGE_ID);


ALTER TABLE T_FAMILY_MEDIA_IMAGE ADD CONSTRAINT FK_T_FAMILY_MEDIA_IMAGE_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_MEDIA_IMAGE ADD CONSTRAINT FK_T_FAMILY_MEDIA_IMAGE_1 FOREIGN KEY (IMAGE_ID) REFERENCES T_MEDIA_IMAGE (IMAGE_ID);


ALTER TABLE T_RELATION_MEDIA_VIDEO ADD CONSTRAINT FK_T_RELATION_MEDIA_VIDEO_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_RELATION_MEDIA_VIDEO ADD CONSTRAINT FK_T_RELATION_MEDIA_VIDEO_1 FOREIGN KEY (VIDEO_ID) REFERENCES T_MEDIA_VIDEO (VIDEO_ID);


ALTER TABLE T_FAMILY_MEDIA_VIDEO ADD CONSTRAINT FK_T_FAMILY_MEDIA_VIDEO_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_MEDIA_VIDEO ADD CONSTRAINT FK_T_FAMILY_MEDIA_VIDEO_1 FOREIGN KEY (VIDEO_ID) REFERENCES T_MEDIA_VIDEO (VIDEO_ID);


ALTER TABLE T_RELATION_MEDIA_AUDIO ADD CONSTRAINT FK_T_RELATION_MEDIA_AUDIO_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_RELATION_MEDIA_AUDIO ADD CONSTRAINT FK_T_RELATION_MEDIA_AUDIO_1 FOREIGN KEY (AUDIO_ID) REFERENCES T_MEDIA_AUDIO (AUDIO_ID);


ALTER TABLE T_FAMILY_MEDIA_AUDIO ADD CONSTRAINT FK_T_FAMILY_MEDIA_AUDIO_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_MEDIA_AUDIO ADD CONSTRAINT FK_T_FAMILY_MEDIA_AUDIO_1 FOREIGN KEY (AUDIO_ID) REFERENCES T_MEDIA_AUDIO (AUDIO_ID);


ALTER TABLE T_FAMILY_RELATION ADD CONSTRAINT FK_T_FAMILY_RELATION_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_RELATION ADD CONSTRAINT FK_T_FAMILY_RELATION_1 FOREIGN KEY (RELATION_FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);


COMMENT ON TABLE BIOGRAPHY_TEMPLATE IS '传记模板';
COMMENT ON COLUMN BIOGRAPHY_TEMPLATE.TEMPLATE_ID IS '模板ID';
COMMENT ON COLUMN BIOGRAPHY_TEMPLATE.TEMPLATE_PATH IS '模板路径';
COMMENT ON COLUMN BIOGRAPHY_TEMPLATE.TEMPLATE_NAME IS '模板名称';
COMMENT ON COLUMN BIOGRAPHY_TEMPLATE.TEMPLATE_DESCRIPTION IS '模板描述';
COMMENT ON TABLE T_MEDIA IS '多媒体信息';
COMMENT ON COLUMN T_MEDIA.MEDIA_ID IS '多媒体信息ID';
COMMENT ON COLUMN T_MEDIA.MEDIA_TIME IS '发生时间';
COMMENT ON COLUMN T_MEDIA.MEDIA_PLACE IS '发生地点';
COMMENT ON COLUMN T_MEDIA.MEDIAL_URL IS '引用URL';
COMMENT ON COLUMN T_MEDIA.MEDIA_URL_PARAM IS '引用URL参数';
COMMENT ON COLUMN T_MEDIA.MEDIA_BRIEF IS '内容简介';
COMMENT ON TABLE T_MEMBER IS '成员';
COMMENT ON COLUMN T_MEMBER.MEMBER_ID IS '成员ID';
COMMENT ON COLUMN T_MEMBER.MEMBER_NAME IS '姓名';
COMMENT ON COLUMN T_MEMBER.MEMBER_BIRTHDAY IS '生年日月';
COMMENT ON COLUMN T_MEMBER.MEMBER_DEADFLG IS '生卒Flg';
COMMENT ON COLUMN T_MEMBER.MEMBER_DEADDAY IS '卒年日月';
COMMENT ON COLUMN T_MEMBER.MEMBER_SEX IS '性别';
COMMENT ON COLUMN T_MEMBER.MEMBER_BIRTHPLACE IS '出生地';
COMMENT ON COLUMN T_MEMBER.MEMBER_DEADPALCE IS '离世地';
COMMENT ON COLUMN T_MEMBER.MEMBER_PHACEPHOTO IS '头像';
COMMENT ON TABLE T_MEDIA_TEXT IS '文本信息';
COMMENT ON COLUMN T_MEDIA_TEXT.TEXT_ID IS '文本信息ID';
COMMENT ON COLUMN T_MEDIA_TEXT.TEXT_CONTENT IS '文本内容';
COMMENT ON COLUMN T_MEDIA_TEXT.TEXT_TYPE IS '文本类型(日志/经历)';
COMMENT ON COLUMN T_MEDIA_TEXT.TEXT_SUMMARY IS '文本摘要';
COMMENT ON COLUMN T_MEDIA_TEXT.MEDIA_ID IS '多媒体信息ID';
COMMENT ON TABLE M_AUTHORITY IS '权限一览表';
COMMENT ON COLUMN M_AUTHORITY.AUTHORITY_ID IS '权限ID';
COMMENT ON COLUMN M_AUTHORITY.AUTHORITY_NAME IS '权限名称';
COMMENT ON TABLE T_MEDIA_IMAGE IS '照片信息';
COMMENT ON COLUMN T_MEDIA_IMAGE.IMAGE_ID IS '照片信息ID';
COMMENT ON COLUMN T_MEDIA_IMAGE.IMAGE_FORMAT IS '照片格式';
COMMENT ON COLUMN T_MEDIA_IMAGE.IMAGE_SIZE IS '照片大小';
COMMENT ON COLUMN T_MEDIA_IMAGE.IMAGE_PATH IS '照片路径';
COMMENT ON COLUMN T_MEDIA_IMAGE.IMAGE_SUMMARY IS '照片缩小图';
COMMENT ON COLUMN T_MEDIA_IMAGE.MEDIA_ID IS '多媒体信息ID';
COMMENT ON TABLE T_USER IS '用户';
COMMENT ON COLUMN T_USER.USER_ID IS '用户ID';
COMMENT ON COLUMN T_USER.USER_MAIL IS '邮箱';
COMMENT ON COLUMN T_USER.USER_PASSWORD IS '密码';
COMMENT ON COLUMN T_USER.USER_PHONENO IS '联系电话';
COMMENT ON COLUMN T_USER.USER_ADDRESS IS '联系地址';
COMMENT ON COLUMN T_USER.MEMBER_ID IS '成员ID';
COMMENT ON TABLE T_MESSAGE IS '留言';
COMMENT ON COLUMN T_MESSAGE.MESSAGE_ID IS '留言ID(0.1.2..)';
COMMENT ON COLUMN T_MESSAGE.MESSAGE_SOURCE_TYPE IS '留言者类型';
COMMENT ON COLUMN T_MESSAGE.MESSAGE_SORCE_NAME IS '留言者姓名';
COMMENT ON COLUMN T_MESSAGE.MESSAGE_CONTEXT IS '留言内容';
COMMENT ON COLUMN T_MESSAGE.MESSAGE_TIME IS '留言时间';
COMMENT ON COLUMN T_MESSAGE.MESSAGE_LEVEL IS '重要级别';
COMMENT ON COLUMN T_MESSAGE.MESSAGE_STATUS IS '留言状态（未读，已读，删除）';
COMMENT ON COLUMN T_MESSAGE.MESSAGE_CONTACE IS '留言者联系方式';
COMMENT ON COLUMN T_MESSAGE.USER_ID IS '用户ID';
COMMENT ON TABLE M_ALL_HERALDRY IS '百家姓家徽';
COMMENT ON COLUMN M_ALL_HERALDRY.ID IS 'ID';
COMMENT ON COLUMN M_ALL_HERALDRY.HERALDRY_NAME IS '姓氏';
COMMENT ON COLUMN M_ALL_HERALDRY.HERALDRY_DESCRIPT IS '图腾说明';
COMMENT ON COLUMN M_ALL_HERALDRY.HERALDRY_PATH IS '图片路径';
COMMENT ON TABLE T_MEDIA_VIDEO IS '视频信息';
COMMENT ON COLUMN T_MEDIA_VIDEO.VIDEO_ID IS '视频信息ID';
COMMENT ON COLUMN T_MEDIA_VIDEO.VEDIO_FORMAT IS '视频格式';
COMMENT ON COLUMN T_MEDIA_VIDEO.VIDEO_SIZE IS '视频大小';
COMMENT ON COLUMN T_MEDIA_VIDEO.VIDEO_PATH IS '视频路径';
COMMENT ON COLUMN T_MEDIA_VIDEO.VIDEO_SUMMARY IS '视频摘要';
COMMENT ON COLUMN T_MEDIA_VIDEO.MEDIA_ID IS '多媒体信息ID';
COMMENT ON TABLE T_ACCESS IS '访问方式';
COMMENT ON COLUMN T_ACCESS.ACCESS_ID IS '访问方式ID';
COMMENT ON COLUMN T_ACCESS.ACCESS_SHORT_URL IS '访问短URL';
COMMENT ON COLUMN T_ACCESS.ACCESS_NORMAL_URL IS '访问长URL';
COMMENT ON COLUMN T_ACCESS.ACCESS_ERCODE IS '访问二维码';
COMMENT ON TABLE T_CEMETERY IS '陵园';
COMMENT ON COLUMN T_CEMETERY.CEMETERY_ID IS '陵园ID';
COMMENT ON COLUMN T_CEMETERY.CEMETERY_NAME IS '陵园名称';
COMMENT ON COLUMN T_CEMETERY.CEMETERY_ADDRESS IS '陵园地址';
COMMENT ON COLUMN T_CEMETERY.CEMETERY_MAP IS '陵园地图';
COMMENT ON COLUMN T_CEMETERY.CEMETERY_URL IS '陵园官网';
COMMENT ON COLUMN T_CEMETERY.CEMETERY_MAIL IS '陵园mail';
COMMENT ON COLUMN T_CEMETERY.CEMETERY_IPHONE IS '陵园电话';
COMMENT ON COLUMN T_CEMETERY.CEMETERY_STATUS IS '陵园状态';
COMMENT ON COLUMN T_CEMETERY.CEMETERY_PROVIDER_TYPE IS '提供者区分';
COMMENT ON COLUMN T_CEMETERY.CEMETERY_PROVIDER_CONTACT IS '提供者联系方式';
COMMENT ON TABLE T_MEDIA_AUDIO IS '音频信息';
COMMENT ON COLUMN T_MEDIA_AUDIO.AUDIO_ID IS '音频信息ID';
COMMENT ON COLUMN T_MEDIA_AUDIO.AUDIO_FORMAT IS '音频格式';
COMMENT ON COLUMN T_MEDIA_AUDIO.AUDIO_SIZE IS '音频大小';
COMMENT ON COLUMN T_MEDIA_AUDIO.AUDIO_PATH IS '音频路径';
COMMENT ON COLUMN T_MEDIA_AUDIO.MEDIA_ID IS '多媒体信息ID';
COMMENT ON TABLE T_RELATION IS '亲族';
COMMENT ON COLUMN T_RELATION.RELATION_ID IS '亲族ID';
COMMENT ON COLUMN T_RELATION.RELATION_NEEDPWD IS '访问是否需要密码';
COMMENT ON COLUMN T_RELATION.RELATION_PASSWORD IS '访问密码';
COMMENT ON COLUMN T_RELATION.USER_ID IS '用户ID';
COMMENT ON COLUMN T_RELATION.TEMPLATE_ID IS '模板ID';
COMMENT ON COLUMN T_RELATION.FAMILY_MEMBER_ID IS '家族成员ID';
COMMENT ON COLUMN T_RELATION.MEMBER_ID IS '成员ID';
COMMENT ON TABLE T_RELATION_ACCESS IS '亲族访问';
COMMENT ON COLUMN T_RELATION_ACCESS.RELATION_ID IS '亲族ID';
COMMENT ON COLUMN T_RELATION_ACCESS.ACCESS_ID IS '访问方式ID';
COMMENT ON TABLE T_RELATION_PRIVACE IS '亲族隐私管理';
COMMENT ON COLUMN T_RELATION_PRIVACE.RELATION_ID IS '亲族ID';
COMMENT ON TABLE T_GRAVE IS '墓碑信息';
COMMENT ON COLUMN T_GRAVE.GRAVE_ID IS '墓碑ID';
COMMENT ON COLUMN T_GRAVE.GRAVE_EPITAPH IS '墓志铭';
COMMENT ON COLUMN T_GRAVE.GRAVE_PRAYER IS '祷文';
COMMENT ON COLUMN T_GRAVE.RELATION_ID IS '亲族ID';
COMMENT ON COLUMN T_GRAVE.GRAVE_IMG IS '墓碑图片';
COMMENT ON COLUMN T_GRAVE.GRAVE_CEMETERY_NAME IS '所属墓园';
COMMENT ON COLUMN T_GRAVE.GRAVE_CEMETERY_ADDRESS IS '墓碑地址';
COMMENT ON COLUMN T_GRAVE.CEMETERY_ID IS '陵园ID';
COMMENT ON TABLE T_GRAVE_CONTACT IS '墓碑联系人';
COMMENT ON COLUMN T_GRAVE_CONTACT.GRAVE_CONTACT_ID IS 'ID';
COMMENT ON COLUMN T_GRAVE_CONTACT.CONTACT_RELATION IS '墓主关系';
COMMENT ON COLUMN T_GRAVE_CONTACT.CONTACT_NAMW IS '姓名';
COMMENT ON COLUMN T_GRAVE_CONTACT.CONTACT_IPHONE IS '联系电话';
COMMENT ON COLUMN T_GRAVE_CONTACT.CONTACT_MAIL IS 'Mail';
COMMENT ON COLUMN T_GRAVE_CONTACT.CONTACT_ADDRESS IS '联系地址';
COMMENT ON COLUMN T_GRAVE_CONTACT.GRAVE_ID IS '墓碑ID';
COMMENT ON TABLE T_FAMILY IS '家族';
COMMENT ON COLUMN T_FAMILY.FAMILY_ID IS '家族ID';
COMMENT ON COLUMN T_FAMILY.FAMILY_MEMBER_NUMBER IS '家族人数';
COMMENT ON COLUMN T_FAMILY.FAMILY_CREATETIME IS '创建时间';
COMMENT ON COLUMN T_FAMILY.FAMILY_HERALDRY IS '家徽';
COMMENT ON COLUMN T_FAMILY.FAMILY_INJUNCTION IS '家训';
COMMENT ON COLUMN T_FAMILY.FAMILY_PASSWORD IS '家族访问密码';
COMMENT ON COLUMN T_FAMILY.FAMILY_PASSWORD_FLG IS '是否需要密码';
COMMENT ON COLUMN T_FAMILY.FAMILY_DESCRIPT IS '家族描述';
COMMENT ON COLUMN T_FAMILY.DELETE_FLG IS '删除Flg(0:未删除，1:删除，2:预删除)';
COMMENT ON COLUMN T_FAMILY.USER_ID IS '用户ID';
COMMENT ON TABLE T_FAMILY_NOTICE IS '家族公告';
COMMENT ON COLUMN T_FAMILY_NOTICE.FAMILY_ID IS '家族ID';
COMMENT ON COLUMN T_FAMILY_NOTICE.NOTICE_CONTENT IS '公告内容';
COMMENT ON COLUMN T_FAMILY_NOTICE.NOTICE_LEVEL IS '重要级别';
COMMENT ON COLUMN T_FAMILY_NOTICE.NOTICE_DATE IS '公告日期';
COMMENT ON COLUMN T_FAMILY_NOTICE.NOTICE_END_DATE IS '公告结束日期';
COMMENT ON TABLE T_FAMILY_MEMBER IS '家族成员';
COMMENT ON COLUMN T_FAMILY_MEMBER.FAMILY_MEMBER_ID IS '家族成员ID';
COMMENT ON COLUMN T_FAMILY_MEMBER.FAMILY_ID IS '家族ID';
COMMENT ON COLUMN T_FAMILY_MEMBER.RELATION_ID IS '亲族ID';
COMMENT ON COLUMN T_FAMILY_MEMBER.USER_ID_1 IS '用户ID_1';
COMMENT ON COLUMN T_FAMILY_MEMBER.FAMILY_MEMBER_GENERATION IS '第几代';
COMMENT ON COLUMN T_FAMILY_MEMBER.PARENT_ID IS '父亲ID';
COMMENT ON COLUMN T_FAMILY_MEMBER.MOTHER_ID IS '母亲ID';
COMMENT ON COLUMN T_FAMILY_MEMBER.WIFE_ID IS '妻子';
COMMENT ON COLUMN T_FAMILY_MEMBER.MEMBER_TYPE IS '成员区分';
COMMENT ON COLUMN T_FAMILY_MEMBER.MEMBER_ID IS '成员ID';
COMMENT ON TABLE T_FAMILY_MEMBER_AUTHORITY IS '家族成员权限';
COMMENT ON COLUMN T_FAMILY_MEMBER_AUTHORITY.FAMILY_MEMBER_ID IS '家族成员ID';
COMMENT ON COLUMN T_FAMILY_MEMBER_AUTHORITY.FAMILY_ID IS '家族ID';
COMMENT ON COLUMN T_FAMILY_MEMBER_AUTHORITY.AUTHORITY_ID IS '权限ID';
COMMENT ON COLUMN T_FAMILY_MEMBER_AUTHORITY.AUTHORITY_STATUS IS '权限状态';
COMMENT ON TABLE T_FAMILY_APPLY IS '家族申请表';
COMMENT ON COLUMN T_FAMILY_APPLY.APPLY_ID IS '申请ID';
COMMENT ON COLUMN T_FAMILY_APPLY.USER_ID IS '用户ID';
COMMENT ON COLUMN T_FAMILY_APPLY.FAMILY_ID IS '家族ID';
COMMENT ON COLUMN T_FAMILY_APPLY.FAMILY_MEMBER_ID IS '父亲ID';
COMMENT ON COLUMN T_FAMILY_APPLY.APPLY_FAMILY_ADMIN IS '家族管理者ID';
COMMENT ON COLUMN T_FAMILY_APPLY.APPLY_STATUS IS '申请状态';
COMMENT ON COLUMN T_FAMILY_APPLY.APPLY_COMMENT IS '申请Comment';
COMMENT ON COLUMN T_FAMILY_APPLY.REPLY_COMMENT IS '回复Comment';
COMMENT ON COLUMN T_FAMILY_APPLY.MEMBER_ID IS '成员ID';
COMMENT ON TABLE T_FAMILY_ACCESS IS '家族访问';
COMMENT ON COLUMN T_FAMILY_ACCESS.FAMILY_ID IS '家族ID';
COMMENT ON COLUMN T_FAMILY_ACCESS.ACCESS_ID IS '访问方式ID';
COMMENT ON TABLE T_MEMORY IS '悼念信息';
COMMENT ON COLUMN T_MEMORY.MEMORY_ID IS 'ID';
COMMENT ON COLUMN T_MEMORY.MEMOEY_CONTENT IS '悼念内容';
COMMENT ON COLUMN T_MEMORY.MEMORY_DATE IS '悼念日期';
COMMENT ON COLUMN T_MEMORY.MEMORY_AUTHOR IS '悼念者';
COMMENT ON COLUMN T_MEMORY.MEMORY_ISPUBLIC IS '是否公开';
COMMENT ON COLUMN T_MEMORY.MEMORY_DELETEFLG IS '是否删除';
COMMENT ON COLUMN T_MEMORY.RELATION_ID IS '亲族ID';
COMMENT ON COLUMN T_MEMORY.MEMORY_IMAGE IS '相关照片';
COMMENT ON TABLE T_RELATION_MEDIA_TEXT IS '文本信息_亲族';
COMMENT ON COLUMN T_RELATION_MEDIA_TEXT.RELATION_ID IS '亲族ID';
COMMENT ON COLUMN T_RELATION_MEDIA_TEXT.TEXT_ID IS '文本信息ID';
COMMENT ON TABLE T_FAMILY_MEDIA_TEXT IS '文本信息_家族';
COMMENT ON COLUMN T_FAMILY_MEDIA_TEXT.FAMILY_ID IS '家族ID';
COMMENT ON COLUMN T_FAMILY_MEDIA_TEXT.TEXT_ID IS '文本信息ID';
COMMENT ON TABLE T_RELATION_MEDIA_IMAGE IS '照片信息_亲族';
COMMENT ON COLUMN T_RELATION_MEDIA_IMAGE.RELATION_ID IS '亲族ID';
COMMENT ON COLUMN T_RELATION_MEDIA_IMAGE.IMAGE_ID IS '照片信息ID';
COMMENT ON TABLE T_FAMILY_MEDIA_IMAGE IS '照片信息_家族';
COMMENT ON COLUMN T_FAMILY_MEDIA_IMAGE.FAMILY_ID IS '家族ID';
COMMENT ON COLUMN T_FAMILY_MEDIA_IMAGE.IMAGE_ID IS '照片信息ID';
COMMENT ON TABLE T_RELATION_MEDIA_VIDEO IS '视频信息_亲族';
COMMENT ON COLUMN T_RELATION_MEDIA_VIDEO.RELATION_ID IS '亲族ID';
COMMENT ON COLUMN T_RELATION_MEDIA_VIDEO.VIDEO_ID IS '视频信息ID';
COMMENT ON TABLE T_FAMILY_MEDIA_VIDEO IS '视频信息_家族';
COMMENT ON COLUMN T_FAMILY_MEDIA_VIDEO.FAMILY_ID IS '家族ID';
COMMENT ON COLUMN T_FAMILY_MEDIA_VIDEO.VIDEO_ID IS '视频信息ID';
COMMENT ON TABLE T_RELATION_MEDIA_AUDIO IS '音频信息_亲族';
COMMENT ON COLUMN T_RELATION_MEDIA_AUDIO.RELATION_ID IS '亲族ID';
COMMENT ON COLUMN T_RELATION_MEDIA_AUDIO.AUDIO_ID IS '音频信息ID';
COMMENT ON TABLE T_FAMILY_MEDIA_AUDIO IS '音频信息_家族';
COMMENT ON COLUMN T_FAMILY_MEDIA_AUDIO.FAMILY_ID IS '家族ID';
COMMENT ON COLUMN T_FAMILY_MEDIA_AUDIO.AUDIO_ID IS '音频信息ID';
COMMENT ON TABLE T_FAMILY_RELATION IS '关联家族';
COMMENT ON COLUMN T_FAMILY_RELATION.FAMILY_ID IS '家族ID';
COMMENT ON COLUMN T_FAMILY_RELATION.RELATION_FAMILY_ID IS '关联家族ID';
COMMENT ON COLUMN T_FAMILY_RELATION.RELATION_DES IS '关联关系';


