CREATE TABLE BIOGRAPHY_TEMPLATE (
 TEMPLATE_ID DECIMAL(10) NOT NULL,
 TEMPLATE_PATH VARCHAR(30),
 TEMPLATE_NAME VARCHAR(20),
 TEMPLATE_DESCRIPTION VARCHAR(20)
);

ALTER TABLE BIOGRAPHY_TEMPLATE ADD CONSTRAINT PK_BIOGRAPHY_TEMPLATE PRIMARY KEY (TEMPLATE_ID);


CREATE TABLE T_MEDIA (
 MEDIA_ID CHAR(10) NOT NULL,
 MEDIA_TIME CHAR(10),
 MEDIA_PLACE CHAR(10),
 MEDIAL_URL CHAR(10),
 MEDIA_URL_PARAM CHAR(10),
 MEDIA_BRIEF CHAR(10)
);

ALTER TABLE T_MEDIA ADD CONSTRAINT PK_T_MEDIA PRIMARY KEY (MEDIA_ID);


CREATE TABLE T_MEMBER (
 MEMBER_ID DECIMAL(10) NOT NULL,
 MEMBER_NAME VARCHAR(20),
 MEMBER_BIRTHDAY DATE,
 MEMBER_DEADFLG CHAR(1),
 MEMBER_DEADDAY DATE,
 MEMBER_SEX CHAR(1),
 MEMBER_BIRTHPLACE VARCHAR(30),
 MEMBER_DEADPALCE VARCHAR(30),
 MEMBER_PHACEPHOTO DECIMAL(100000)
);

ALTER TABLE T_MEMBER ADD CONSTRAINT PK_T_MEMBER PRIMARY KEY (MEMBER_ID);


CREATE TABLE T_MEDIA_TEXT (
 TEXT_ID CHAR(10) NOT NULL,
 TEXT_CONTENT CHAR(10),
 TEXT_TYPE CHAR(10),
 TEXT_SUMMARY CHAR(10),
 MEDIA_ID CHAR(10)
);

ALTER TABLE T_MEDIA_TEXT ADD CONSTRAINT PK_T_MEDIA_TEXT PRIMARY KEY (TEXT_ID);


CREATE TABLE M_AUTHORITY (
 AUTHORITY_ID CHAR(10) NOT NULL,
 AUTHORITY_NAME CHAR(10)
);

ALTER TABLE M_AUTHORITY ADD CONSTRAINT PK_M_AUTHORITY PRIMARY KEY (AUTHORITY_ID);


CREATE TABLE T_MEDIA_IMAGE (
 IMAGE_ID CHAR(10) NOT NULL,
 IMAGE_FORMAT CHAR(10),
 IMAGE_SIZE CHAR(10),
 IMAGE_PATH CHAR(10),
 IMAGE_SUMMARY CHAR(10),
 MEDIA_ID CHAR(10)
);

ALTER TABLE T_MEDIA_IMAGE ADD CONSTRAINT PK_T_MEDIA_IMAGE PRIMARY KEY (IMAGE_ID);


CREATE TABLE T_USER (
 USER_ID DECIMAL(10) NOT NULL,
 USER_MAIL VARCHAR(20) NOT NULL,
 USER_PASSWORD VARCHAR(15) NOT NULL,
 USER_PHONENO VARCHAR(30),
 USER_ADDRESS VARCHAR(30),
 MEMBER_ID DECIMAL(10) NOT NULL
);

ALTER TABLE T_USER ADD CONSTRAINT PK_T_USER PRIMARY KEY (USER_ID);


CREATE TABLE T_MESSAGE (
 MESSAGE_ID DECIMAL(10) NOT NULL,
 MESSAGE_SOURCE_TYPE CHAR(1) DEFAULT '0' NOT NULL,
 MESSAGE_SORCE_NAME VARCHAR(30) DEFAULT 'ä«óù?' NOT NULL,
 MESSAGE_CONTEXT VARCHAR(500),
 MESSAGE_TIME DATE DEFAULT 'NOW()' NOT NULL,
 MESSAGE_LEVEL CHAR(1) DEFAULT '0' NOT NULL,
 MESSAGE_STATUS CHAR(1) DEFAULT '0' NOT NULL,
 MESSAGE_CONTACE VARCHAR(30),
 USER_ID DECIMAL(10)
);

ALTER TABLE T_MESSAGE ADD CONSTRAINT PK_T_MESSAGE PRIMARY KEY (MESSAGE_ID);


CREATE TABLE M_ALL_HERALDRY (
 ID CHAR(10) NOT NULL,
 HERALDRY_NAME CHAR(10),
 HERALDRY_DESCRIPT CHAR(10),
 HERALDRY_PATH CHAR(10)
);

ALTER TABLE M_ALL_HERALDRY ADD CONSTRAINT PK_M_ALL_HERALDRY PRIMARY KEY (ID);


CREATE TABLE T_MEDIA_VIDEO (
 VIDEO_ID CHAR(10) NOT NULL,
 VEDIO_FORMAT CHAR(10),
 VIDEO_SIZE CHAR(10),
 VIDEO_PATH CHAR(10),
 VIDEO_SUMMARY CHAR(10),
 MEDIA_ID CHAR(10)
);

ALTER TABLE T_MEDIA_VIDEO ADD CONSTRAINT PK_T_MEDIA_VIDEO PRIMARY KEY (VIDEO_ID);


CREATE TABLE T_ACCESS (
 ACCESS_ID DECIMAL(10) NOT NULL,
 ACCESS_SHORT_URL INT,
 ACCESS_NORMAL_URL CHAR(10),
 ACCESS_ERCODE CHAR(10)
);

ALTER TABLE T_ACCESS ADD CONSTRAINT PK_T_ACCESS PRIMARY KEY (ACCESS_ID);


CREATE TABLE T_CEMETERY (
 CEMETERY_ID CHAR(10) NOT NULL,
 CEMETERY_NAME CHAR(10),
 CEMETERY_ADDRESS CHAR(10),
 CEMETERY_MAP CHAR(10),
 CEMETERY_URL CHAR(10),
 CEMETERY_MAIL CHAR(10),
 CEMETERY_IPHONE CHAR(10),
 CEMETERY_STATUS CHAR(10),
 CEMETERY_PROVIDER_TYPE CHAR(10),
 CEMETERY_PROVIDER_CONTACT CHAR(10)
);

ALTER TABLE T_CEMETERY ADD CONSTRAINT PK_T_CEMETERY PRIMARY KEY (CEMETERY_ID);


CREATE TABLE T_MEDIA_AUDIO (
 AUDIO_ID CHAR(10) NOT NULL,
 AUDIO_FORMAT CHAR(10),
 AUDIO_SIZE CHAR(10),
 AUDIO_PATH CHAR(10),
 MEDIA_ID CHAR(10)
);

ALTER TABLE T_MEDIA_AUDIO ADD CONSTRAINT PK_T_MEDIA_AUDIO PRIMARY KEY (AUDIO_ID);


CREATE TABLE T_RELATION (
 RELATION_ID DECIMAL(10) NOT NULL,
 RELATION_NEEDPWD CHAR(1),
 RELATION_PASSWORD TIMESTAMP WITH TIME ZONE(10),
 USER_ID DECIMAL(10),
 TEMPLATE_ID DECIMAL(10),
 FAMILY_MEMBER_ID DECIMAL(10),
 MEMBER_ID DECIMAL(10) NOT NULL
);

ALTER TABLE T_RELATION ADD CONSTRAINT PK_T_RELATION PRIMARY KEY (RELATION_ID);


CREATE TABLE T_RELATION_ACCESS (
 RELATION_ID DECIMAL(10) NOT NULL,
 ACCESS_ID DECIMAL(10)
);

ALTER TABLE T_RELATION_ACCESS ADD CONSTRAINT PK_T_RELATION_ACCESS PRIMARY KEY (RELATION_ID);


CREATE TABLE T_RELATION_PRIVACE (
 RELATION_ID DECIMAL(10) NOT NULL
);

ALTER TABLE T_RELATION_PRIVACE ADD CONSTRAINT PK_T_RELATION_PRIVACE PRIMARY KEY (RELATION_ID);


CREATE TABLE T_GRAVE (
 GRAVE_ID CHAR(10) NOT NULL,
 GRAVE_EPITAPH CHAR(10),
 GRAVE_PRAYER CHAR(10),
 RELATION_ID DECIMAL(10) NOT NULL,
 GRAVE_IMG CHAR(10),
 GRAVE_CEMETERY_NAME CHAR(10),
 GRAVE_CEMETERY_ADDRESS CHAR(10),
 CEMETERY_ID CHAR(10)
);

ALTER TABLE T_GRAVE ADD CONSTRAINT PK_T_GRAVE PRIMARY KEY (GRAVE_ID);


CREATE TABLE T_GRAVE_CONTACT (
 GRAVE_CONTACT_ID CHAR(10) NOT NULL,
 CONTACT_RELATION CHAR(10),
 CONTACT_NAMW CHAR(10),
 CONTACT_IPHONE CHAR(10),
 CONTACT_MAIL CHAR(10),
 CONTACT_ADDRESS CHAR(10),
 GRAVE_ID CHAR(10)
);

ALTER TABLE T_GRAVE_CONTACT ADD CONSTRAINT PK_T_GRAVE_CONTACT PRIMARY KEY (GRAVE_CONTACT_ID);


CREATE TABLE T_FAMILY (
 FAMILY_ID CHAR(10) NOT NULL,
 FAMILY_MEMBER_NUMBER CHAR(10),
 FAMILY_CREATETIME DATE,
 FAMILY_HERALDRY CHAR(10),
 FAMILY_INJUNCTION CHAR(10),
 FAMILY_PASSWORD CHAR(10),
 FAMILY_PASSWORD_FLG CHAR(10),
 FAMILY_DESCRIPT CHAR(10),
 DELETE_FLG CHAR(10),
 USER_ID DECIMAL(10)
);

ALTER TABLE T_FAMILY ADD CONSTRAINT PK_T_FAMILY PRIMARY KEY (FAMILY_ID);


CREATE TABLE T_FAMILY_NOTICE (
 FAMILY_ID CHAR(10) NOT NULL,
 NOTICE_CONTENT CHAR(10),
 NOTICE_LEVEL CHAR(10),
 NOTICE_DATE CHAR(10),
 NOTICE_END_TIME CHAR(10)
);

ALTER TABLE T_FAMILY_NOTICE ADD CONSTRAINT PK_T_FAMILY_NOTICE PRIMARY KEY (FAMILY_ID);


CREATE TABLE T_FAMILY_MEMBER (
 FAMILY_MEMBER_ID CHAR(10) NOT NULL,
 FAMILY_ID CHAR(10) NOT NULL,
 RELATION_ID DECIMAL(10),
 USER_ID_1 DECIMAL(10),
 FAMILY_MEMBER_GENERATION CHAR(10),
 PARENT_ID CHAR(10),
 MOTHER_ID CHAR(10),
 WIFE_ID CHAR(10),
 MEMBER_TYPE CHAR(10),
 MEMBER_ID DECIMAL(10)
);

ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT PK_T_FAMILY_MEMBER PRIMARY KEY (FAMILY_MEMBER_ID);


CREATE TABLE T_FAMILY_MEMBER_AUTHORITY (
 FAMILY_MEMBER_ID CHAR(10) NOT NULL,
 FAMILY_ID CHAR(10) NOT NULL,
 AUTHORITY_ID CHAR(10),
 AUTHORITY_STATUS CHAR(10)
);

ALTER TABLE T_FAMILY_MEMBER_AUTHORITY ADD CONSTRAINT PK_T_FAMILY_MEMBER_AUTHORITY PRIMARY KEY (FAMILY_MEMBER_ID,FAMILY_ID);


CREATE TABLE T_FAMILY_APPLY (
 APPLY_ID CHAR(10) NOT NULL,
 USER_ID DECIMAL(10),
 FAMILY_ID CHAR(10),
 FAMILY_MEMBER_ID CHAR(10),
 APPLY_FAMILY_ADMIN DECIMAL(10),
 APPLY_STATUS CHAR(10),
 APPLY_COMMENT CHAR(10),
 REPLY_COMMENT CHAR(10),
 MEMBER_ID DECIMAL(10)
);

ALTER TABLE T_FAMILY_APPLY ADD CONSTRAINT PK_T_FAMILY_APPLY PRIMARY KEY (APPLY_ID);


CREATE TABLE T_FAMILY_ACCESS (
 FAMILY_ID CHAR(10) NOT NULL,
 ACCESS_ID DECIMAL(10)
);

ALTER TABLE T_FAMILY_ACCESS ADD CONSTRAINT PK_T_FAMILY_ACCESS PRIMARY KEY (FAMILY_ID);


CREATE TABLE T_MEMORY (
 MEMORY_ID CHAR(10) NOT NULL,
 MEMOEY_CONTENT CHAR(10),
 MEMORY_DATE CHAR(10),
 MEMORY_AUTHOR CHAR(10),
 MEMORY_ISPUBLIC CHAR(10),
 MEMORY_DELETEFLG CHAR(10),
 RELATION_ID DECIMAL(10) NOT NULL,
 MEMORY_IMAGE CHAR(10)
);

ALTER TABLE T_MEMORY ADD CONSTRAINT PK_T_MEMORY PRIMARY KEY (MEMORY_ID);


CREATE TABLE T_RELATION_MEDIA_TEXT (
 RELATION_ID DECIMAL(10) NOT NULL,
 TEXT_ID CHAR(10) NOT NULL
);

ALTER TABLE T_RELATION_MEDIA_TEXT ADD CONSTRAINT PK_T_RELATION_MEDIA_TEXT PRIMARY KEY (RELATION_ID,TEXT_ID);


CREATE TABLE T_FAMILY_MEDIA_TEXT (
 FAMILY_ID CHAR(10) NOT NULL,
 TEXT_ID CHAR(10) NOT NULL
);

ALTER TABLE T_FAMILY_MEDIA_TEXT ADD CONSTRAINT PK_T_FAMILY_MEDIA_TEXT PRIMARY KEY (FAMILY_ID,TEXT_ID);


CREATE TABLE T_RELATION_MEDIA_IMAGE (
 RELATION_ID DECIMAL(10) NOT NULL,
 IMAGE_ID CHAR(10) NOT NULL
);

ALTER TABLE T_RELATION_MEDIA_IMAGE ADD CONSTRAINT PK_T_RELATION_MEDIA_IMAGE PRIMARY KEY (RELATION_ID,IMAGE_ID);


CREATE TABLE T_FAMILY_MEDIA_IMAGE (
 FAMILY_ID CHAR(10) NOT NULL,
 IMAGE_ID CHAR(10) NOT NULL
);

ALTER TABLE T_FAMILY_MEDIA_IMAGE ADD CONSTRAINT PK_T_FAMILY_MEDIA_IMAGE PRIMARY KEY (FAMILY_ID,IMAGE_ID);


CREATE TABLE T_RELATION_MEDIA_VIDEO (
 RELATION_ID DECIMAL(10) NOT NULL,
 VIDEO_ID CHAR(10) NOT NULL
);

ALTER TABLE T_RELATION_MEDIA_VIDEO ADD CONSTRAINT PK_T_RELATION_MEDIA_VIDEO PRIMARY KEY (RELATION_ID,VIDEO_ID);


CREATE TABLE T_FAMILY_MEDIA_VIDEO (
 FAMILY_ID CHAR(10) NOT NULL,
 VIDEO_ID CHAR(10) NOT NULL
);

ALTER TABLE T_FAMILY_MEDIA_VIDEO ADD CONSTRAINT PK_T_FAMILY_MEDIA_VIDEO PRIMARY KEY (FAMILY_ID,VIDEO_ID);


CREATE TABLE T_RELATION_MEDIA_AUDIO (
 RELATION_ID DECIMAL(10) NOT NULL,
 AUDIO_ID CHAR(10) NOT NULL
);

ALTER TABLE T_RELATION_MEDIA_AUDIO ADD CONSTRAINT PK_T_RELATION_MEDIA_AUDIO PRIMARY KEY (RELATION_ID,AUDIO_ID);


CREATE TABLE T_FAMILY_MEDIA_AUDIO (
 FAMILY_ID CHAR(10) NOT NULL,
 AUDIO_ID CHAR(10) NOT NULL
);

ALTER TABLE T_FAMILY_MEDIA_AUDIO ADD CONSTRAINT PK_T_FAMILY_MEDIA_AUDIO PRIMARY KEY (FAMILY_ID,AUDIO_ID);


CREATE TABLE T_FAMILY_RELATION (
 FAMILY_ID CHAR(10) NOT NULL,
 RELATION_FAMILY_ID CHAR(10),
 RELATION_TYPE CHAR(10)
);

ALTER TABLE T_FAMILY_RELATION ADD CONSTRAINT PK_T_FAMILY_RELATION PRIMARY KEY (FAMILY_ID);


ALTER TABLE T_MEDIA_TEXT ADD CONSTRAINT FK_T_MEDIA_TEXT_0 FOREIGN KEY (MEDIA_ID) REFERENCES T_MEDIA (MEDIA_ID);


ALTER TABLE T_MEDIA_IMAGE ADD CONSTRAINT FK_T_MEDIA_IMAGE_0 FOREIGN KEY (MEDIA_ID) REFERENCES T_MEDIA (MEDIA_ID);


ALTER TABLE T_USER ADD CONSTRAINT FK_T_USER_0 FOREIGN KEY (MEMBER_ID) REFERENCES T_MEMBER (MEMBER_ID);


ALTER TABLE T_MESSAGE ADD CONSTRAINT FK_T_MESSAGE_0 FOREIGN KEY (USER_ID) REFERENCES T_USER (USER_ID);


ALTER TABLE T_MEDIA_VIDEO ADD CONSTRAINT FK_T_MEDIA_VIDEO_0 FOREIGN KEY (MEDIA_ID) REFERENCES T_MEDIA (MEDIA_ID);


ALTER TABLE T_MEDIA_AUDIO ADD CONSTRAINT FK_T_MEDIA_AUDIO_0 FOREIGN KEY (MEDIA_ID) REFERENCES T_MEDIA (MEDIA_ID);


ALTER TABLE T_RELATION ADD CONSTRAINT FK_T_RELATION_0 FOREIGN KEY (USER_ID) REFERENCES T_USER (USER_ID);
ALTER TABLE T_RELATION ADD CONSTRAINT FK_T_RELATION_1 FOREIGN KEY (TEMPLATE_ID) REFERENCES BIOGRAPHY_TEMPLATE (TEMPLATE_ID);
ALTER TABLE T_RELATION ADD CONSTRAINT FK_T_RELATION_2 FOREIGN KEY (MEMBER_ID) REFERENCES T_MEMBER (MEMBER_ID);


ALTER TABLE T_RELATION_ACCESS ADD CONSTRAINT FK_T_RELATION_ACCESS_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_RELATION_ACCESS ADD CONSTRAINT FK_T_RELATION_ACCESS_1 FOREIGN KEY (ACCESS_ID) REFERENCES T_ACCESS (ACCESS_ID);


ALTER TABLE T_RELATION_PRIVACE ADD CONSTRAINT FK_T_RELATION_PRIVACE_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);


ALTER TABLE T_GRAVE ADD CONSTRAINT FK_T_GRAVE_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_GRAVE ADD CONSTRAINT FK_T_GRAVE_1 FOREIGN KEY (CEMETERY_ID) REFERENCES T_CEMETERY (CEMETERY_ID);


ALTER TABLE T_GRAVE_CONTACT ADD CONSTRAINT FK_T_GRAVE_CONTACT_0 FOREIGN KEY (GRAVE_ID) REFERENCES T_GRAVE (GRAVE_ID);


ALTER TABLE T_FAMILY ADD CONSTRAINT FK_T_FAMILY_0 FOREIGN KEY (USER_ID) REFERENCES T_USER (USER_ID);


ALTER TABLE T_FAMILY_NOTICE ADD CONSTRAINT FK_T_FAMILY_NOTICE_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);


ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_1 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_2 FOREIGN KEY (USER_ID_1) REFERENCES T_USER (USER_ID);
ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_3 FOREIGN KEY (PARENT_ID) REFERENCES T_FAMILY_MEMBER (FAMILY_MEMBER_ID);
ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_4 FOREIGN KEY (MOTHER_ID) REFERENCES T_FAMILY_MEMBER (FAMILY_MEMBER_ID);
ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_5 FOREIGN KEY (WIFE_ID) REFERENCES T_FAMILY_MEMBER (FAMILY_MEMBER_ID);
ALTER TABLE T_FAMILY_MEMBER ADD CONSTRAINT FK_T_FAMILY_MEMBER_6 FOREIGN KEY (MEMBER_ID) REFERENCES T_MEMBER (MEMBER_ID);


ALTER TABLE T_FAMILY_MEMBER_AUTHORITY ADD CONSTRAINT FK_T_FAMILY_MEMBER_AUTHORITY_0 FOREIGN KEY (FAMILY_MEMBER_ID) REFERENCES T_FAMILY_MEMBER (FAMILY_MEMBER_ID);
ALTER TABLE T_FAMILY_MEMBER_AUTHORITY ADD CONSTRAINT FK_T_FAMILY_MEMBER_AUTHORITY_1 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_MEMBER_AUTHORITY ADD CONSTRAINT FK_T_FAMILY_MEMBER_AUTHORITY_2 FOREIGN KEY (AUTHORITY_ID) REFERENCES M_AUTHORITY (AUTHORITY_ID);


ALTER TABLE T_FAMILY_APPLY ADD CONSTRAINT FK_T_FAMILY_APPLY_0 FOREIGN KEY (USER_ID) REFERENCES T_USER (USER_ID);
ALTER TABLE T_FAMILY_APPLY ADD CONSTRAINT FK_T_FAMILY_APPLY_1 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_APPLY ADD CONSTRAINT FK_T_FAMILY_APPLY_2 FOREIGN KEY (FAMILY_MEMBER_ID) REFERENCES T_FAMILY_MEMBER (FAMILY_MEMBER_ID);
ALTER TABLE T_FAMILY_APPLY ADD CONSTRAINT FK_T_FAMILY_APPLY_3 FOREIGN KEY (APPLY_FAMILY_ADMIN) REFERENCES T_USER (USER_ID);
ALTER TABLE T_FAMILY_APPLY ADD CONSTRAINT FK_T_FAMILY_APPLY_4 FOREIGN KEY (MEMBER_ID) REFERENCES T_MEMBER (MEMBER_ID);


ALTER TABLE T_FAMILY_ACCESS ADD CONSTRAINT FK_T_FAMILY_ACCESS_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_ACCESS ADD CONSTRAINT FK_T_FAMILY_ACCESS_1 FOREIGN KEY (ACCESS_ID) REFERENCES T_ACCESS (ACCESS_ID);


ALTER TABLE T_MEMORY ADD CONSTRAINT FK_T_MEMORY_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);


ALTER TABLE T_RELATION_MEDIA_TEXT ADD CONSTRAINT FK_T_RELATION_MEDIA_TEXT_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_RELATION_MEDIA_TEXT ADD CONSTRAINT FK_T_RELATION_MEDIA_TEXT_1 FOREIGN KEY (TEXT_ID) REFERENCES T_MEDIA_TEXT (TEXT_ID);


ALTER TABLE T_FAMILY_MEDIA_TEXT ADD CONSTRAINT FK_T_FAMILY_MEDIA_TEXT_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_MEDIA_TEXT ADD CONSTRAINT FK_T_FAMILY_MEDIA_TEXT_1 FOREIGN KEY (TEXT_ID) REFERENCES T_MEDIA_TEXT (TEXT_ID);


ALTER TABLE T_RELATION_MEDIA_IMAGE ADD CONSTRAINT FK_T_RELATION_MEDIA_IMAGE_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_RELATION_MEDIA_IMAGE ADD CONSTRAINT FK_T_RELATION_MEDIA_IMAGE_1 FOREIGN KEY (IMAGE_ID) REFERENCES T_MEDIA_IMAGE (IMAGE_ID);


ALTER TABLE T_FAMILY_MEDIA_IMAGE ADD CONSTRAINT FK_T_FAMILY_MEDIA_IMAGE_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_MEDIA_IMAGE ADD CONSTRAINT FK_T_FAMILY_MEDIA_IMAGE_1 FOREIGN KEY (IMAGE_ID) REFERENCES T_MEDIA_IMAGE (IMAGE_ID);


ALTER TABLE T_RELATION_MEDIA_VIDEO ADD CONSTRAINT FK_T_RELATION_MEDIA_VIDEO_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_RELATION_MEDIA_VIDEO ADD CONSTRAINT FK_T_RELATION_MEDIA_VIDEO_1 FOREIGN KEY (VIDEO_ID) REFERENCES T_MEDIA_VIDEO (VIDEO_ID);


ALTER TABLE T_FAMILY_MEDIA_VIDEO ADD CONSTRAINT FK_T_FAMILY_MEDIA_VIDEO_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_MEDIA_VIDEO ADD CONSTRAINT FK_T_FAMILY_MEDIA_VIDEO_1 FOREIGN KEY (VIDEO_ID) REFERENCES T_MEDIA_VIDEO (VIDEO_ID);


ALTER TABLE T_RELATION_MEDIA_AUDIO ADD CONSTRAINT FK_T_RELATION_MEDIA_AUDIO_0 FOREIGN KEY (RELATION_ID) REFERENCES T_RELATION (RELATION_ID);
ALTER TABLE T_RELATION_MEDIA_AUDIO ADD CONSTRAINT FK_T_RELATION_MEDIA_AUDIO_1 FOREIGN KEY (AUDIO_ID) REFERENCES T_MEDIA_AUDIO (AUDIO_ID);


ALTER TABLE T_FAMILY_MEDIA_AUDIO ADD CONSTRAINT FK_T_FAMILY_MEDIA_AUDIO_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_MEDIA_AUDIO ADD CONSTRAINT FK_T_FAMILY_MEDIA_AUDIO_1 FOREIGN KEY (AUDIO_ID) REFERENCES T_MEDIA_AUDIO (AUDIO_ID);


ALTER TABLE T_FAMILY_RELATION ADD CONSTRAINT FK_T_FAMILY_RELATION_0 FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
ALTER TABLE T_FAMILY_RELATION ADD CONSTRAINT FK_T_FAMILY_RELATION_1 FOREIGN KEY (RELATION_FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);


